import psycopg2
import streamlit as st
from food import Food
def get_connection():
    return psycopg2.connect(st.secrets["DATABASE_URL"])
def create_table():
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS foods (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        price INTEGER NOT NULL,
        category TEXT NOT NULL,
        available BOOLEAN NOT NULL DEFAULT TRUE)
                """)
    connection.commit()
    cursor.close()
    connection.close()

def insert_food(food):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    INSERT INTO foods (name, price, category, available)
    VALUES (%s, %s ,%s ,%s)
    """, (
        food.name,
        food.price,
        food.category,
        food.available)
    )
    connection.commit()
    cursor.close()
    connection.close()
@st.cache_data(ttl=300)
def get_all_foods():
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    SELECT id, name, price, category, available
    FROM foods
    ORDER BY id
    """)
    rows = cursor.fetchall()

    cursor.close()
    connection.close()

    foods = []

    for row in rows:
        food_id, name, price, category, available = row
        food = Food(food_id, name, price, category, available)
        foods.append(food)
    return foods

def update_food_name_in_db(food_id, new_name):
    connection = get_connection()
    cursor = connection.cursor()
    cursor.execute("""
    UPDATE foods
    SET name = %s
    WHERE id = %s
    """, (new_name, food_id))
    connection.commit()
    cursor.close()
    connection.close()

def update_food_price_in_db(food_id, new_price):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    UPDATE foods
    SET price = %s
    WHERE id = %s
    """, (new_price, food_id))

    connection.commit()
    cursor.close()
    connection.close()

def update_food_category_in_db(food_id, new_category):
    connection = get_connection()
    cursor = connection.cursor()
    cursor.execute("""
    UPDATE foods
    SET category = %s
    WHERE id = %s
    """, (new_category, food_id))
    connection.commit()
    cursor.close()
    connection.close()
    
def update_food_available_in_db(food_id, new_available):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    UPDATE foods
    set available = %s
    WHERE id = %s
    """, (new_available, food_id))

    connection.commit()
    cursor.close()
    connection.close()

def delete_food(food_id):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
    DELETE FROM foods
    WHERE id = %s
    """, (food_id,))

    connection.commit()
    cursor.close()
    connection.close()

def seed_sample_data():
    foods = get_all_foods()
    if len(foods) == 0:
        food1 = Food(None,"Phở bò", 40000, "Món nước", True)
        food2 = Food(None,"Cơm gà", 35000, "Món cơm", True)
        food3 = Food(None,"Trà đào",25000, "Đồ uống", True)
        insert_food(food1)
        insert_food(food2)
        insert_food(food3)

def get_foods_by_category(category):
    connection = get_connection()
    cursor = connection.cursor()
    cursor.execute("""
        SELECT id, name, price, category, available
        FROM foods
        WHERE category = %s
        """,
        (category,))
    rows = cursor.fetchall()

    cursor.close()
    connection.close()

    foods = []
    for row in rows:
        food_id, name, price, category, available = row
        food = Food(food_id, name, price, category, available)
        foods.append(food)
    return foods

def get_foods_by_category_and_available(category, available_filter):
    connection = get_connection()
    cursor = connection.cursor()

    sql = """
        SELECT id, name, price, category, available
        FROM foods
        WHERE 1 = 1
    """

    params = []

    if category != "Tất cả":
        sql += " AND category = %s"
        params.append(category)

    if available_filter == "Còn bán":
        sql += " AND available = %s"
        params.append(True)

    elif available_filter == "Hết bán":
        sql += " AND available = %s"
        params.append(False)

    cursor.execute(sql, tuple(params))

    rows = cursor.fetchall()

    cursor.close()
    connection.close()

    foods = []

    for row in rows:
        food = Food(
            id=row[0],
            name=row[1],
            price=row[2],
            category=row[3],
            available=row[4]
        )
        foods.append(food)

    return foods

def get_foods_by_filters(category, available_filter, search_keyword):
    connection = get_connection()
    cursor = connection.cursor()

    sql = """
        SELECT id, name, price, category, available
        FROM foods
        WHERE 1 = 1
    """

    params = []

    if category != "Tất cả":
        sql += " AND category = %s"
        params.append(category)

    if available_filter == "Còn bán":
        sql += " AND available = %s"
        params.append(True)

    elif available_filter == "Hết bán":
        sql += " AND available = %s"
        params.append(False)

    if search_keyword.strip() != "":
        sql += " AND name ILIKE %s"
        params.append(f"%{search_keyword.strip()}%")

    cursor.execute(sql, tuple(params))

    rows = cursor.fetchall()

    cursor.close()
    connection.close()

    foods = []

    for row in rows:
        food = Food(
            id=row[0],
            name=row[1],
            price=row[2],
            category=row[3],
            available=row[4]
        )
        foods.append(food)

    return foods

def get_foods_by_filters(category, available_filter, search_keyword, sort_option):
    connection = get_connection()
    cursor = connection.cursor()

    sql = """
        SELECT id, name, price, category, available
        FROM foods
        WHERE 1 = 1
    """

    params = []

    if category != "Tất cả":
        sql += " AND category = %s"
        params.append(category)

    if available_filter == "Còn bán":
        sql += " AND available = %s"
        params.append(True)

    elif available_filter == "Hết bán":
        sql += " AND available = %s"
        params.append(False)

    if search_keyword.strip() != "":
        sql += " AND name ILIKE %s"
        params.append(f"%{search_keyword.strip()}%")

    if sort_option == "Tên A-Z":
        sql += " ORDER BY name ASC"
    
    elif sort_option == "Giá tăng dần":
        sql += " ORDER BY price ASC"

    elif sort_option == "Giá giảm dần":
        sql += " ORDER BY price DESC"

    cursor.execute(sql, tuple(params))

    rows = cursor.fetchall()

    cursor.close()
    connection.close()

    foods = []

    for row in rows:
        food = Food(
            id=row[0],
            name=row[1],
            price=row[2],
            category=row[3],
            available=row[4]
        )
        foods.append(food)

    return foods

def update_food_in_db(food_id, new_name, new_price, new_category, new_available):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute(
        """
        UPDATE foods
        SET name = %s,
            price = %s,
            category = %s,
            available = %s
        WHERE id = %s
        """,
        (new_name, new_price, new_category, new_available, food_id)
    )

    connection.commit()

    cursor.close()
    connection.close()